name: data-test

on: 
  push:
    branches: [ "main" ]

jobs:
  data1:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA1 }}
  data2:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA2 }}
  data3:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA3 }}
  data4:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA4 }}
  data5:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA5 }}
  data6:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA6 }}
  data7:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA7 }}
  data8:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA8 }}
  data9:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA9 }}
  data10:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA10 }}
