name: VTEST
on: 
  workflow_dispatch:
   inputs:
      crdauthcode:
        description: 'Enter ChromeRemoteDesktop Headless code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Linux System Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Setting Up the Ubuntu Environment
      run: sudo bash linux.sh
      env:
        CHROME_HEADLESS_CODE: ${{ github.event.inputs.crdauthcode }}
        GOOGLE_REMOTE_PIN: ${{ github.event.inputs.pincode }}
    - name: Keep Running Ubuntu System and keepAlive
    ##  if: ${{ failure() }}
      run: sleep 6h
