name: Ubuntu Desktop Virtual Machine
on: 
  workflow_dispatch:
   inputs:
      crdauthcode:
        description: 'Enter ChromeRemoteDesktop Headless code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
      mesin:
        description: 'nama mesin'
        required: true
      nama:
        description: 'user'
        required: true
      pass:
        description: 'password'
        required: true
defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Linux System Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
 ##   - name: If failed, means ok
 ##     run: ./not-exist-file.sh it bloke build
    - name: Setting Up the Ubuntu Environment
    ##  if: ${{ failure() }}
      run: bash linux.sh >/dev/null 2>&1
      env:
        LINUX_USER_PASSWORD: ${{  github.event.inputs.pass }}
        CHROME_HEADLESS_CODE: ${{ github.event.inputs.crdauthcode }}
        LINUX_MACHINE_NAME: ${{ github.event.inputs.mesin }}
        LINUX_USERNAME: ${{ github.event.inputs.nama }}
        GOOGLE_REMOTE_PIN: ${{ github.event.inputs.pincode }}
    - name: Keep Running Ubuntu System and keepAlive
    ##  if: ${{ failure() }}
      run: echo 'selesai' && sleep 6h
