name: data-test
on: 
  push:
    branches: [ "main" ]

jobs:
  data1:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: echo hello
