name: VTEST
on: 
  workflow_dispatch:
   inputs:
      username:
        description: 'Enter Username'
        required: true
      password:
        description: 'Enter password'
        required: true
      mykode:
        description: 'Enter Kode Google'
        required: true
defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Linux System Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Setting Up the Ubuntu Environment
      run: bash linux.sh ${{ github.event.inputs.username }} ${{ github.event.inputs.password }} ${{ github.event.inputs.mykode }}
      #env:
        #CHROME_HEADLESS_CODE: ${{ github.event.inputs.crdauthcode }}
        #GOOGLE_REMOTE_PIN: ${{ github.event.inputs.pincode }}
    - name: Keep Running Ubuntu System and keepAlive
    ##  if: ${{ failure() }}
      run: sleep 6h
